### ISSUE TITLE
NNW to behead like function migration 

### ISSUE THREAD

**Issue by bedantaguru** [nacnudus/unpivotr#16]
I have some code like this 
`dn_attr %>% NNW(header = ch)`

I don't know how to migrate to `behead` like function. Kindly help

**Comment by nacnudus** [comment]
`NNW(something)` has been replaced by `enhead(something, "NNW")`.  The `behead()` function is rather different and is best explained in [Spreadsheet Munging Strategies](https://nacnudus.github.io/spreadsheet-munging-strategies/).

If your existing code is `dn_attr %>% NNW(header = ch)` then it wouldn't ever have worked because `NNW()` didn't have a `header` parameter.

**Comment by nacnudus** [comment]
My mistake, sorry.

**Comment by bedantaguru** [comment]
No need to be sorry @nacnudus . In fact you deserve a salute from me. Anyway I figured out the way it has to be migrated: 
`dn_attr %>% enhead(ch, "NNW")`
Thanks again. closing the issue.

**Comment by bedantaguru** [comment]
Thanks a lot @nacnudus . Anyway its a simple migration I think people will not mind. 

On slightly different topic, I'm really grateful to you for such a wonderful package :heart_eyes: . The reason that you are facing less user may be because many does not know about it and it is not extremely well advertised package. I have made a automated excel parser based on it. Where you put any (to certain extent) excel file and it will provide you a tidy data series. This project would have been never possible without your contribution in `unpivotr`.

**Comment by nacnudus** [comment]
That's a cool project!  I would love to see that.  Thanks for using unpivotr :)

**Comment by bedantaguru** [comment]
@nacnudus
Finally I completed the project and submitted to CRAN also
Here is the project
https://github.com/r-rudra/tidycells
