### ISSUE TITLE
Feature Request: Allow behead() to optionally work within a sheet

### ISSUE THREAD

**Issue by billdenney** [nacnudus/unpivotr#46]
I often get data with many sheets in a workbook formatted the same way.  In my use case, it is data from many animal studies measuring the same type of thing (e.g. measuring cholesterol changes in an animal's blood).  To work with these data, I currently split my data by sheet (using `dplyr::nest()`) then iterate over the new list of data.frames.

I think it would be helpful to have a new `behead_within()` function that splits the data by one or more columns (I assume it would most commonly be , `sheet`), operates on the split data, and then puts it back together for output.

If this is of interest, please let me know, and I can make a PR.

**Comment by nacnudus** [comment]
Thank you for this suggestion.  I think [this example](https://nacnudus.github.io/spreadsheet-munging-strategies/same-table-in-several-worksheetsfiles-using-the-sheetfile-name.html) is relevant, because it also uses `dplyr::nest()`, and wraps the unpivotr steps in a function that is iterated over the nested sheets.

In the context of #45, this would work well.  However, as it stands, there would be several calls to `behead_within()`, and each one would have to nest and unnest the whole dataset, which is often a slow operation.

Perhaps there's a way to do it with a `dplyr::group_by()` grouped data frame.  It didn't used to be possible, but dplyr has changed a lot since I last tried.  I'd be happy to review a PR if you can get that to work.

**Comment by billdenney** [comment]
I just submitted a PR.  If accepted, then the example should probably also be updated to use `group_by()` instead of `nest()`.
