### ISSUE TITLE
Loading library rccmisc together with unpivotr breaks something

### ISSUE THREAD

**Issue by StaffanBetner** [nacnudus/unpivotr#50]
As you can see below, the library rccmisc breaks something with unpivotr.

``` r
library(unpivotr)
cells <- tibble::tribble(
  ~X1, ~adult, ~juvenile,
  "LION",    855,       677,
  "male",    496,       322,
  "female",    359,       355,
  "TIGER",    690,       324,
  "male",    381,       222,
  "female",    309,       102
)
cells <- as_cells(cells, col_names = TRUE)

cells %>%
  behead_if(chr == toupper(chr), direction = "left-up", name = "species") %>%
  behead("left", "sex") %>%
  behead("up", "age") %>%
  dplyr::select(species, sex, age, population = dbl)
#> # A tibble: 12 x 4
#>    species sex    age      population
#>    <chr>   <chr>  <chr>         <dbl>
#>  1 LION    <NA>   adult           855
#>  2 LION    male   adult           496
#>  3 LION    female adult           359
#>  4 LION    <NA>   juvenile        677
#>  5 LION    male   juvenile        322
#>  6 LION    female juvenile        355
#>  7 TIGER   <NA>   adult           690
#>  8 TIGER   male   adult           381
#>  9 TIGER   female adult           309
#> 10 TIGER   <NA>   juvenile        324
#> 11 TIGER   male   juvenile        222
#> 12 TIGER   female juvenile        102

library(rccmisc)

cells %>%
  behead_if(chr == toupper(chr), direction = "left-up", name = "species") %>%
  behead("left", "sex") %>%
  behead("up", "age") %>%
  dplyr::select(species, sex, age, population = dbl)
#> Error: Can't subset columns that don't exist.
#> x Column `row` doesn't exist.
```

<sup>Created on 2021-11-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by nacnudus** [comment]
Thank you for reporting this.  It was interesting to debug.

The rccmisc package defines `cut.integer()` and registers it as an S3 'generic'.  That means that anywhere that `cut()` is called with an integer argument, `rccmisc:::cut.integer()` is used instead of `base:::cut.default()` (or any of the other `cut.something()` methods in base).  The unexpected behaviour of `rccmisc:::cut.integer()` trips up unpivotr.  What the author of rccmisc has done is, probably unwittingly, ["exceedingly bad manners"](https://adv-r.hadley.nz/s3.html#s3-arguments)(!), according to Hadley Wickham, because it can cause this kind of nuisance.

There are two ways to fix this.  One way is that I could explicitly call `base:::cut.default()` in unpivotr.  I'd prefer not to.  The other way is for you to run `registerS3method("cut", "integer", cut.default, envir = parent.frame())` before using any unpivotr functions.  That will effectively deregister `rccc::cut.integer()`.  You can reinstate it later with `registerS3method("cut", "integer", rccmisc:::cut.integer, envir = parent.frame())`.  Below is an example.

```r
library(unpivotr)
library(rccmisc)

cells <- tibble::tribble(
  ~X1, ~adult, ~juvenile,
  "LION",    855,       677,
  "male",    496,       322,
  "female",    359,       355,
  "TIGER",    690,       324,
  "male",    381,       222,
  "female",    309,       102
)
cells <- as_cells(cells, col_names = TRUE)

# Deactivate rccmisc:::cut.integer()
registerS3method("cut", "integer", cut.default, envir = parent.frame())

# Now unpivotr works
behead_if(cells, chr == toupper(chr), direction = "left-up", name = "species")

# Reinstate rccmisc:::cut.integer() if you need it
registerS3method("cut", "integer", rccmisc:::cut.integer, envir = parent.frame())
```

**Comment by StaffanBetner** [comment]
Thank you for debugging this! I gave up fairly quickly after figuring out which package that was responsible.
