### ISSUE TITLE
data.table alternative: fuzzy_join

### ISSUE THREAD

**Issue by lepennec** [nacnudus/unpivotr#7]
Hi,
I've seen that you are using data.table extended join abilities to perform some joins. There is an alternative package, probably less efficient than data.table, that avoid the tibble -> data.table -> tibble conversion:

Here is a code snipset showing how to use it in your package for instance here in NNW
```
header <- header %>%
  dplyr::select(-row) %>% dplyr::arrange(col) %>% 
  dplyr::mutate(col = col,
                to_col = dplyr::lead(col - 1,
                                     default = Inf))

bag %>% fuzzyjoin::fuzzy_left_join(header,
                                         by = c("col" = "col",
                                                "col" = "to_col"),
                                         match_fun = list(`>=`, `<=`)) %>%
  dplyr::rename(col = col.x) %>% dplyr::select(-col.y, -to_col)
```

I'm not saying this is better than your choice. It just requires less conversion...

Yours,

Erwan

**Comment by nacnudus** [comment]
Hi @lepennec, thanks for the suggestion.

The `fuzzyjoin` package is excellent, and I have used it in other projects.  For this package I chose `data.table` to avoid a Bioconductor dependency on `IRanges`, and because it seemed to be faster, but the round-trip conversion is certainly klunky.  Hopefully one day we can use https://github.com/tidyverse/dplyr/issues/2240.
